
# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/glnds/masl
    steps:
      - checkout
      - run: go get -u github.com/golang/dep/cmd/dep github.com/alecthomas/gometalinter && gometalinter --install
      - run: dep ensure --vendor-only
      - run: go vet ./...
      - run: go test -v ./...
      - run: gometalinter . --disable gocyclo
      - run: go build cmd/masl/masl.go
